name: wp-login-page
recipe: wordpress
config:
  webroot: ./wordpress/
events:
  # Runs composer install and a custom php script after your app starts
  post-start:
  - appserver: cd $LANDO_MOUNT && composer install
tooling:
  setup:
    service: appserver
    description: 'Setup env'
    cmd:
      - echo "➡️ Reset DB ?"
      - if [ -f /app/wordpress/wp-config.php ]; then echo "wp-config exists reset DB" && wp db reset --yes --path=/app/wordpress ; else echo "No wp-config.php, no reset" ; fi
      - echo "➡️ Reset config"
      - if [ -f /app/wordpress/wp-config.php ]; then echo "wp-config exists deleting it" && rm -f /app/wordpress/wp-config.php; else echo "No wp-config.php, no rm" ; fi
      - echo "➡️ Create config"
      - wp config create --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=database --path=/app/wordpress
      - echo "➡️ Install WP"
      - wp core multisite-install --url=https://wp-login-page.lndo.site --title="Wp login page" --admin_password=admin --admin_email=admin@admin.fr --path=/app/wordpress --skip-email
      - echo "➡️ Add new sites"
      - wp site create --slug=site-1 --title="Site 1" --path=/app/wordpress
      - wp site create --slug=site-2 --title="Site 2" --path=/app/wordpress
      - wp site create --slug=site-3 --title="Site 3" --path=/app/wordpress
      - wp site create --slug=site-4 --title="Site 4" --path=/app/wordpress
      - cp /app/tests/bin/htaccess /app/wordpress/.htaccess
      - mkdir -p /app/wordpress/wp-content/mu-plugins/
      - ln -s /app/wp-login-page.php /app/wordpress/wp-content/mu-plugins/wp-login-page.php